/*!
 * FilePondPluginImageOverlay 1.0.6
 * Licensed under MIT, https://opensource.org/licenses/MIT/
 * Please visit undefined for details.
 */

/* eslint-disable */

!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):(e=e||self).FilePondPluginImageOverlay=t()}(this,(function(){"use strict";const e=e=>/^image/.test(e.type),t=e=>{let t=document.createElement("span");return t.className="filepond--magnify-icon",t.title=e,t},n=e=>{const t=document.createElement("div");t.className="filepond--fullsize-overlay";const n=document.createElement("div"),o=URL.createObjectURL(e.file);n.className="image-container",n.style.backgroundImage="url("+o+")",i(o,n);let d=document.getElementsByTagName("body")[0];t.appendChild(n),d.appendChild(t),t.addEventListener("click",()=>t.remove())},i=(e,t)=>{const n=Math.max(document.documentElement.clientWidth,window.innerWidth||0),i=Math.max(document.documentElement.clientHeight,window.innerHeight||0);((e,t)=>{let n=new Image;n.onload=()=>{const e=n.naturalWidth,i=n.naturalHeight;n=null,t(e,i)},n.src=e})(e,(e,o)=>{(e>n||o>i)&&(t.style.backgroundSize="contain")})},o=i=>{const{addFilter:o,utils:d}=i,{Type:l,createRoute:c}=d;return o("CREATE_VIEW",i=>{const{is:o,view:d,query:l}=i;if(!o("file"))return;d.registerWriter(c({DID_LOAD_ITEM:({root:i,props:o})=>{const{id:d}=o,c=l("GET_ITEM",d);if(!c||c.archived||!e(c.file))return;const a=i.query("GET_LABEL_BUTTON_IMAGE_OVERLAY");((e,i,o)=>{const d=i.querySelector(".filepond--file-info-main"),l=t(o);d.prepend(l),l.addEventListener("click",()=>n(e)),window.setTimeout(()=>{const t=i.querySelector(".filepond--image-preview");t&&(t.classList.add("clickable"),t.addEventListener("click",()=>n(e)))},1e3)})(c,i.element,a),i.dispatch("DID_MEDIA_PREVIEW_CONTAINER_CREATE",{id:d})}},({root:t,props:n})=>{const{id:i}=n,o=l("GET_ITEM",i);e(o.file)&&t.rect.element.hidden}))}),{options:{labelButtonImageOverlay:["Open image in overlay",l.STRING]}}};return"undefined"!=typeof window&&void 0!==window.document&&document.dispatchEvent(new CustomEvent("FilePond:pluginloaded",{detail:o})),o}));
